### ISSUE TITLE
小游戏 Sprite 无法加载图片

### ISSUE THREAD

**Issue by bitzip** [spritejs/sprite-wxapp#14]
**game.js**
* dice.png 跟 game.js 在相同文件夹

```
import './js/libs/symbol';
import {Label, Scene, Layer, Sprite, Group} from './js/libs/sprite-wxapp';

const scene = new Scene()
const bglayer = scene.layer('bglayer');
let s = new Sprite('./dice.png')
s.attr({
  size: [200, 200],
  pos: [50, 50]
})
bglayer.append(s)
```

编译时页面报错
```
VM4974:1 gameThirdScriptError
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
    at http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:20223:38
    at Array.forEach (<anonymous>)
    at ResSprite.render (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:20187:18)
    at ResSprite.draw (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:1863:14)
    at ExLayer.drawSprites (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:18975:19)
    at ExLayer.drawSprites (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:6778:128)
    at ExLayer.renderRepaintAll (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:19002:12)
    at ExLayer.draw (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:18933:7)
    at http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:18888:22
    at http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:9079:9
```

另外：
* 使用 scene.preload 方法报相同错误。

**Comment by akira-cn** [comment]
图片路径不对吧？微信小程序中路径应当相对于page而不是相对于js文件。报这个错是因为小程序没有加载到对应的图片。

**Comment by bitzip** [comment]
@akira-cn 项目用在「小游戏」非「小程序」，应该不是没有加载到文件的问题，因为使用原生的 `new Image('./dice.png')` 可以加载到，如果用 `new Sprite('./dice.png')` 在 console 里没有看到发送 network 请求

**Comment by akira-cn** [comment]
那如果这样呢？

**Comment by akira-cn** [comment]
那如果这样呢？

```js
const image = new Image('./dice.png');
image.onload(() => {
    const sprite = new Sprite();
    sprite.attr('textures', image);
});
```

**Comment by bitzip** [comment]
@akira-cn 
```Javascript
const image = new Image();
image.src = './dice.png'
image.onload = function() {
  let s = new Sprite()
  s.attr({
    size: [200, 200],
    pos: [50, 50],
    textures: image
  })
  bglayer.append(s) 
}
```

报相同的错误 🙁
```
VM4974:1 gameThirdScriptError
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
    at http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:20223:38
    at Array.forEach (<anonymous>)
    at ResSprite.render (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:20187:18)
    at ResSprite.draw (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:1863:14)
    at ExLayer.drawSprites (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:18975:19)
    at ExLayer.drawSprites (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:6778:128)
    at ExLayer.renderRepaintAll (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:19002:12)
    at ExLayer.draw (http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:18933:7)
    at http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:18888:22
    at http://127.0.0.1:39519/game/js/libs/sprite-wxapp.js:9079:9
```

**Comment by akira-cn** [comment]
我修了一下，更新到最新版本就好了
